#!/bin/bash -e
# zmogrify - Run dracut and configure grub to boot with root on zfs.

mount_boot_efi() {
  # Mount efi boot partition using entry in /etc/fstab
  mount /boot/efi

  # Make sure we unmount it - even if there are errors
  trap umount_boot_efi EXIT
}

umount_boot_efi() {
  # Finished with efi parition
  umount /boot/efi
}

setup_boot_efi() {
  # Get the kernel release string
  kver=${1:-"$(uname -r)"}

  # Recreate the initramfs for this kernel
  sh -x /usr/bin/dracut -fv --kver $kver

  mount_boot_efi

  # Rebuild the grub config
  grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg

  # Set grub boot menu item 0 as the default
  grubby --set-default-index 0

  # Copy the zfs grub modules from the grub install into the efi boot partition
  mkdir -p /boot/efi/EFI/fedora/x86_64-efi
  cp -a /usr/lib/grub/x86_64-efi/zfs* /boot/efi/EFI/fedora/x86_64-efi
}

setup_boot_efi

