#!/bin/bash -e
# zmogrify - Run dracut and configure grub to boot with root on zfs.

mount_boot_efi() {
  # Mount efi boot partition using entry in /etc/fstab
  mount /boot/efi

  # Make sure we unmount it - even if there are errors
  trap umount_boot_efi EXIT
}

umount_boot_efi() {
  # Finished with efi parition
  umount /boot/efi
}

setup_boot_efi() {
  # Get the kernel release string
  local installedKernel=$(ls /boot/vmlinuz*x86_64 | cut -d'-' -f2-)
  local runningKernel=$(uname -r)
  local zver 

  if [[ "${installedKernel}" != "${runningKernel}" ]]; then
    # zfs and spl modules need rebuilt
    zver=$(rpm -q zfs | cut -d'-' -f2)
    
    dkms install -m spl -v ${zver} -k ${installedKernel}
    dkms install -m zfs -v ${zver} -k ${installedKernel}

  fi 

  # Recreate the initramfs for this kernel
  sh -x /usr/bin/dracut -fv --kver $installedKernel

  if ! -e /boot/initramfs-${installedKernel}.img; then
    echo "Missing file: /boot/initramfs-${installedKernel}.img"
    exit 1
  fi
  
  if ! (lsinitrd -k ${installedKernel} | grep "zfs.ko"); then
    echo "Installed initramfs doesnt contain zfs.ko"
    exit 1
  fi

  mount_boot_efi

  # Rebuild the grub config
  grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg

  # Set grub boot menu item 0 as the default
  grubby --set-default-index 0

  if ! grep "${installedKernel}" /boot/efi/EFI/fedora/grub.cfg; then
    echo "Installed Kernel not mentioned in grub.cfg"
    exit 1
  fi

  # Copy the zfs grub modules from the os filesystem into the efi boot partition
  mkdir -p /boot/efi/EFI/fedora/x86_64-efi
  cp -a /usr/lib/grub/x86_64-efi/zfs* /boot/efi/EFI/fedora/x86_64-efi
}

setup_boot_efi

